name: E2E Test

on:
  workflow_run:
    workflows: 
      - Frontend Deployment
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    
    # services:
    #   postgress:
    #     image: postgress:15
    #     ports:
    #       - 5432:5432
    #     env:
    #       POSTGRES_USER: testuser
    #       POSTGRES_PASSWORD: testpass
    #       POSTGRES_DB: testdb

    #     options: >-
    #       --health-cmd="pg_isready -U testuser"
    #       --health-interval=10s
    #       --health-timeout=5s
    #       --health-retries=5

        # env:
        #   DATABASE_URL: postgres://testuser:testpass@localhost:5432/testdb


    steps:
    - uses: actions/checkout@v4

    # - name: Setup Node.js
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: '20'
    #     cache: 'npm'
    #     cache-dependency-path: frontend/package-lock.json

    # - name: Install dependencies
    #   working-directory: ./frontend  
    #   run: npm install  
    
    - name: Install dependencies
      working-directory: ./e2e-tests
      run: npm install
    
    - name: Run Cypress
      working-directory: ./e2e-tests
      run: 
          npm run cypress:run

    - name: Run tests with reports
      working-directory: ./e2e-tests
      run: npm run test:report 