name: E2E Test

on:
  workflow_run:
    workflows: 
      - Frontend Deployment
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CYPRESS_baseUrl: https://team2-cicdws-bucket.s3.us-east-1.amazonaws.com/index.html

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies  
      working-directory: ./frontend  
      run: npm install  
    
    - name: Install dependencies
      working-directory: ./e2e-tests
      run: npm install
    
    - name: Run Cypress
      working-directory: ./e2e-tests
      run: 
          npm run cypress:run

    - name: Run tests with reports
      working-directory: ./e2e-tests
      run: npm run test:report 