name: E2E Test

on:
  workflow_run:
    workflows: 
      - Frontend Deployment
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      working-directory: ./e2e-tests
      run: npm install
    
    - name: Run Cypress
      working-directory: ./e2e-tests
      run: 
          npm run cypress:run

    - name: Run tests with reports
      working-directory: ./e2e-tests
      run: npm run test:report 