name: Frontend Deployment
on:
  push:
    branches:
        - team2-lasata


jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Specify Node.js version 20
    - name: Install dependencies
      run: |
        cd frontend
        npm install
    - name: build Frontend
      run: |
        cd frontend
        npm run build
      env:
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}



    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to s3
      run: aws s3 sync frontend/build/ ${{ secrets.AWS_S3_BUCKET_URI }} --delete

    - name: Invalidate CloudFront
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
